---
- name: Check if wp-cli exists
  stat: path="{{ usr_bin }}/wp"
  register: wpcli_exist
  tags:
    - always

- name: Updating wp-cli
  shell: "{{ usr_bin }}/wp cli update --yes"
  when: wpcli_exist.stat.exists
  tags:
    - wp
    - update

- name: Download wp-cli
  get_url:
    url="https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    dest="{{ usr_bin }}/wp"
    force_basic_auth=yes
    mode=0755
  when: not wpcli_exist.stat.exists
  tags:
    - wp
    - install
