---
- name: Install PHP and related packages
  vars:
    packages:
      - php
      - php-fpm
      - php-cli
      - php-curl
      - php-pdo
      - php-mysqlnd
  dnf:
    pkg: "{{ packages }}"
    update_cache: true
    state: latest
