---
- name: Initialize image with required packages for wordpress
  hosts: default
  become: true
  vars_files: ./vars/main.yml

  roles:
    - apache
    - php
    - permissions
    - wp_cli
    - wordpress
