name: Generate Golden Image

on:
  workflow_dispatch:
  schedule:
    # triggers the workflow every day at 13:00 UTC (mid-night AEST time)
    - cron: '0 13 * * *'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  generate:
    name: Generate new golden image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packer

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Run `packer init`
        id: init
        run: |
          packer init -var-file="variables.pkrvars.hcl" .

      - name: Run `packer validate`
        id: validate
        run: |
          packer validate -var-file="variables.pkrvars.hcl" .

      - name: Generate the image
        run: |
          packer build -var-file="variables.pkrvars.hcl" .
        env:
          PKR_VAR_aws_profile: default
